language: python

python:
 - 3.6

env:
 - DJANGO=2.1.5

before_install:
 - export DJANGO_SETTINGS_MODULE=ChatIO.settings

install:
 - pip3 install -r requirements.txt

before_script:
 - python3 manage.py makemigrations
 - python3 manage.py migrate

script:
 - black --check ChatIO/
 - black --check chat/
 - python3 manage.py test
